# Generated by Django 4.2.2 on 2023-07-16 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_orderitem_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='refund_amount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
