# Generated by Django 4.2.2 on 2023-07-19 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_refund_amount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitem',
            options={'ordering': ['created_at']},
        ),
    ]
