# Generated by Django 4.2.2 on 2023-07-06 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_brandlogo_brand_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'categories'},
        ),
    ]
