# Generated by Django 4.2.2 on 2023-07-24 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_recentlyviewedproduct'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RecentlyViewedProduct',
        ),
    ]
